# Generated by Django 4.1.4 on 2022-12-10 01:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('front', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='annonce',
            old_name='announcer',
            new_name='annonceur',
        ),
    ]
