export const wilayas = [
  { name: '01-Adrar', value: 'Adrar' },
  { name: '02-Chlef', value: 'Chlef' },
  { name: '03-Laghouat', value: 'Laghouat' },
  { name: '04-Oum-El-Bouaghi', value: 'Oum-El-Bouaghi' },
  { name: '05-Batna', value: 'Batna' },
  { name: '06-Béjaïa', value: 'Béjaïa' },
  { name: '07-Biskra', value: 'Biskra' },
  { name: '08-Béchar', value: 'Béchar' },
  { name: '09-Blida', value: 'Blida' },
  { name: '10-Bouira', value: 'Bouira' },
  { name: '11-Tamanrasset', value: 'Tamanrasset' },
  { name: '12-Tébessa', value: 'Tébessa' },
  { name: '13-Tlemcen', value: 'Tlemcen' },
  { name: '14-Tiaret', value: 'Tiaret' },
  { name: '15-Tizi-Ouzou', value: 'Tizi-Ouzou' },
  { name: '16-Alger', value: 'Alger' },
  { name: '17-Djelfa', value: 'Djelfa' },
  { name: '18-Jijel', value: 'Jijel' },
  { name: '19-Sétif', value: 'Sétif' },
  { name: '20-Saïda', value: 'Saïda' },
  { name: '21-Skikda', value: 'Skikda' },
  { name: '22-Sidi Bel Abbès', value: 'Sidi Bel Abbès' },
  { name: '23-Annaba', value: 'Annaba' },
  { name: '24-Guelma', value: 'Guelma' },
  { name: '25-Constantine', value: 'Constantine' },
  { name: '26-Médéa', value: 'Médéa' },
  { name: '27-Mostaganem', value: 'Mostaganem' },
  { name: '28-M’sila', value: 'M’sila' },
  { name: '29-Mascara', value: 'Mascara' },
  { name: '30-Ouargla', value: 'Ouargla' },
  { name: '31-Oran    Said ', value: 'Oran    Said ' },
  { name: '32-El Bayadh', value: 'El Bayadh' },
  { name: '33-Illizi', value: 'Illizi' },
  { name: '34-Bordj Bou Arreridj', value: 'Bordj Bou Arreridj' },
  { name: '35-Boumerdès', value: 'Boumerdès' },
  { name: '36-El-Tarf', value: 'El-Tarf' },
  { name: '37-Tindouf', value: 'Tindouf' },
  { name: '38-Tissemsilt', value: 'Tissemsilt' },
  { name: '39-El-Oued', value: 'El-Oued' },
  { name: '40-Khenchela', value: 'Khenchela' },
  { name: '41-Souk-Ahras', value: 'Souk-Ahras' },
  { name: '42-Tipaza', value: 'Tipaza' },
  { name: '43-Mila', value: 'Mila' },
  { name: '44-Aïn-Defla', value: 'Aïn-Defla' },
  { name: '45-Naâma', value: 'Naâma' },
  { name: '46-Aïn-Témouchent', value: 'Aïn-Témouchent' },
  { name: '47-Ghardaïa', value: 'Ghardaïa' },
  { name: '48-Relizane', value: 'Relizane' },
  { name: '49-El M-Ghair', value: 'El M-Ghair' },
  { name: '50-El Meniaa', value: 'El Meniaa' },
  { name: '51-Ouled Djellal', value: 'Ouled Djellal' },
  { name: '52-Bordj Badji Mokhtar', value: 'Bordj Badji Mokhtar' },
  { name: '53-Béni Abbès', value: 'Béni Abbès' },
  { name: '54-Timimoun', value: 'Timimoun' },
  { name: '55-Touggourt', value: 'Touggourt' },
  { name: '56-Djanet', value: 'Djanet' },
  { name: '57-In Salah', value: 'In Salah' },
  { name: '58-In Guezz', value: 'In Guezz' },
];
