# Generated by Django 4.1.4 on 2022-12-15 13:51

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='contact',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('phone', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='locatlisation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('city', models.CharField(max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='utitlisateur',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=20)),
                ('prenom', models.CharField(max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='annonce',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('categorie', models.CharField(choices=[('V', 'Vente'), ('E', 'Echange'), ('L', 'Location'), ('LV', 'Location pour Vacances')], max_length=12)),
                ('type', models.CharField(choices=[('T', 'Terrain'), ('TA', 'Terrain Agricole'), ('A', 'Appartement'), ('M', 'Maison'), ('B', 'Bungalow')], max_length=12)),
                ('description', models.CharField(max_length=500)),
                ('suface', models.IntegerField()),
                ('prix', models.IntegerField()),
                ('photos', models.ImageField(upload_to='annonce/')),
                ('annonceur', models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, to='agence_api.utitlisateur')),
                ('contact', models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, to='agence_api.contact')),
                ('loc', models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, to='agence_api.locatlisation')),
            ],
        ),
    ]
