# Generated by Django 4.1.4 on 2022-12-15 13:56

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('agence_api', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='annonce',
            name='annonceur',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='agence_api.utitlisateur'),
        ),
        migrations.AlterField(
            model_name='annonce',
            name='contact',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='agence_api.contact'),
        ),
        migrations.AlterField(
            model_name='annonce',
            name='loc',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='agence_api.locatlisation'),
        ),
    ]
