# Generated by Django 4.1.4 on 2022-12-28 14:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('agence_api', '0004_annonce_insertdate_annonce_titre_alter_favoris_user_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='annonce',
            name='insertDate',
            field=models.DateField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='location',
            name='city',
            field=models.CharField(max_length=30),
        ),
    ]
