# Generated by Django 4.1.4 on 2022-12-28 14:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('agence_api', '0005_alter_annonce_insertdate_alter_location_city'),
    ]

    operations = [
        migrations.AlterField(
            model_name='annonce',
            name='insertDate',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
