# Generated by Django 4.1.4 on 2023-01-08 22:37

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('agence_api', '0007_offre_rename_suface_annonce_surface_delete_message_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='favoris',
            name='favDateTime',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='offre',
            name='dateOffre',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
