# Generated by Django 4.1.4 on 2023-02-01 20:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('agence_api', '0008_favoris_favdatetime_offre_dateoffre'),
    ]

    operations = [
        migrations.AddField(
            model_name='location',
            name='adress',
            field=models.CharField(default='alger', max_length=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='location',
            name='lat',
            field=models.FloatField(default=36.7),
        ),
        migrations.AddField(
            model_name='location',
            name='lng',
            field=models.FloatField(default=3),
        ),
        migrations.AddField(
            model_name='location',
            name='wilaya',
            field=models.CharField(default='alger', max_length=30),
            preserve_default=False,
        ),
    ]
