# Generated by Django 4.1.4 on 2023-02-01 21:16

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('agence_api', '0009_location_adress_location_lat_location_lng_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='image',
            name='annonce',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='agence_api.annonce'),
        ),
        migrations.AlterField(
            model_name='image',
            name='path',
            field=models.ImageField(upload_to='annonce_images'),
        ),
    ]
